#!/usr/bin/env python3
# -*- coding: utf-8 -*-

APP_DISPLAY_NAME = "SMS输入校外实习和特殊绩效分数系统"
APP_SIMPLE_NAME = "SMS 学生成绩自动上传系统"
APP_AUTHOR = "教务处 陈九天"
APP_RELEASE_DATE = "2026/7/22"
APP_VERSION = "V2.2"
APP_EXE_BASE_NAME = "SMS成绩上传工具"
APP_EXE_NAME = f"{APP_EXE_BASE_NAME} {APP_VERSION}"
APP_WINDOW_TITLE = f"{APP_SIMPLE_NAME} - {APP_VERSION}"
APP_FOOTER_TEXT = f'"{APP_DISPLAY_NAME}" | {APP_AUTHOR} {APP_RELEASE_DATE} {APP_VERSION}'
